version: "3"
services:
  universalis:
    image: ghcr.io/universalis-ffxiv/universalis:latest
    environment:
      ASPNETCORE_URLS: http://+:4000
    volumes:
      - /home/universalis/sqpack:/sqpack
      - /home/universalis/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 3500m
  watchtower:
    image: containrrr/watchtower
    environment:
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "discord://${ALERTS_CHANNEL_WEBHOOK}" # Format: token@channel
      WATCHTOWER_NOTIFICATION_TEMPLATE: "{{range .}}{{.Time.Format \"2006-01-02 15:04:05\"}} ({{.Level}}): {{.Message}}{{println}}{{end}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/universalis/.docker/config.json:/config.json
    command: --interval 30