version: "3"
services:
  universalis:
    image: ghcr.io/universalis-ffxiv/universalis:latest
    environment:
      ASPNETCORE_URLS: http://+:4001
    volumes:
      - /home/universalis/sqpack:/sqpack
    network_mode: "host"
  watchtower:
    image: containrrr/watchtower
    environment:
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: "${ALERTS_CHANNEL_WEBHOOK}/slack"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: Watchtower
      WATCHTOWER_NOTIFICATION_TEMPLATE: "{{range .}}{{.Time.Format \"2006-01-02 15:04:05\"}} ({{.Level}}): {{.Message}}{{println}}{{end}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/universalis/.docker/config.json:/config.json
    command: --interval 30